export const image = '../images/club.jpg'
export const config = {
  name: 'my-map',
  areas: [
    {
      id: '1',
      title: 'Table 1 - Super Vip',
      shape: 'rect',
      name: '1',
      fillColor: '#eab54d4d',
      strokeColor: 'crimson',
      coords: [30, 35, 60, 55],
    },
    {
      id: '2',
      title: 'Table 2 - 6 persons',
      shape: 'rect',
      name: '2',
      fillColor: '#eab54d4d',
      strokeColor: 'crimson',
      coords: [65, 20, 80, 40],
    },
    {
      id: '3',
      title: 'Table 3 - 6 persons',
      shape: 'rect',
      name: '3',
      fillColor: '#eab54d4d',
      strokeColor: 'crimson',
      coords: [80, 20, 95, 40],
    },
    {
      id: '4',
      title: 'Table 4 - 6 persons',
      shape: 'rect',
      name: '4',
      fillColor: '#eab54d4d',
      strokeColor: 'crimson',
      coords: [95, 20, 110, 40],
    },
    {
      id: '5',
      title: 'Table 4 - 6 persons',
      shape: 'rect',
      name: '5',
      fillColor: '#eab54d4d',
      strokeColor: 'crimson',
      coords: [113, 20, 133, 40],
    },
    {
      id: '5',
      title: 'Table 4 - 6 persons',
      shape: 'rect',
      name: '5',
      fillColor: '#eab54d4d',
      strokeColor: 'crimson',
      coords: [135, 20, 155, 40],
    },
    {
      id: '5',
      title: 'Table 4 - 6 persons',
      shape: 'rect',
      name: '5',
      fillColor: '#eab54d4d',
      strokeColor: 'crimson',
      coords: [158, 20, 178, 40],
    },
    {
      id: '5',
      title: 'Table 4 - 6 persons',
      shape: 'rect',
      name: '5',
      fillColor: '#eab54d4d',
      strokeColor: 'crimson',
      coords: [182, 17, 205, 40],
    },
    {
      id: '5',
      title: 'Table 4 - 6 persons',
      shape: 'rect',
      name: '5',
      fillColor: '#eab54d4d',
      strokeColor: 'crimson',
      coords: [213, 27, 242, 60],
    },
    {
      id: '5',
      title: 'Table 4 - 6 persons',
      shape: 'rect',
      name: '5',
      fillColor: '#eab54d4d',
      strokeColor: 'crimson',
      coords: [192, 52, 214, 70],
    },
    {
      id: '5',
      title: 'Table 4 - 6 persons',
      shape: 'rect',
      name: '5',
      fillColor: '#eab54d4d',
      strokeColor: 'crimson',
      coords: [127, 53, 144, 70],
    },
    {
      id: '5',
      title: 'Table 4 - 6 persons',
      shape: 'rect',
      name: '5',
      fillColor: '#eab54d4d',
      strokeColor: 'crimson',
      coords: [130, 70, 149, 87],
    },
    {
      id: '5',
      title: 'Table 4 - 6 persons',
      shape: 'rect',
      name: '5',
      fillColor: '#eab54d4d',
      strokeColor: 'crimson',
      coords: [155, 72, 173, 89],
    },
    {
      id: '5',
      title: 'Table 4 - 6 persons',
      shape: 'rect',
      name: '5',
      fillColor: '#eab54d4d',
      strokeColor: 'crimson',
      coords: [175, 69, 190, 85],
    },
    {
      id: '5',
      title: 'Table 4 - 6 persons',
      shape: 'rect',
      name: '5',
      fillColor: '#eab54d4d',
      strokeColor: 'crimson',
      coords: [110, 92, 150, 117],
    },
  ],
}
